"""Guests table

Revision ID: aa1ab20804e3
Revises: 
Create Date: 2019-01-05 23:00:11.331669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1ab20804e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('attending', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_email'), 'guest', ['email'], unique=True)
    op.create_index(op.f('ix_guest_name'), 'guest', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_name'), table_name='guest')
    op.drop_index(op.f('ix_guest_email'), table_name='guest')
    op.drop_table('guest')
    # ### end Alembic commands ###
